### ISSUE TITLE
Naming conflicts 

### ISSUE THREAD

**Issue by sandakith** [mioteg/AppServiceEnvironment#1]
We are getting few naming conflicts while doing this, it would be bit helpful if we could document which of the resources need unique names in this environment (right now we believe all resources need unique names). We thought of thinking about this since we are now getting in to deployments and re-deployments.  

VERBOSE: 11:14:36 AM - Checking deployment status in 25 seconds
New-AzureRmResourceGroupDeployment : 11:15:01 AM - Resource Microsoft.Web/hostingEnvir
message '{
  "Code": "Conflict",
  "Message": "A stamp with the specified name already exists in the location MyASE.",

**Comment by mioteg** [comment]
Working on some changes that improve readability and documentation. Also adding uniqueness to storage account.

**Comment by sandakith** [comment]
Great! Thanks. We are in the process getting each part up and running and for the most part we are successful. We will try this again soon.

**Comment by mioteg** [comment]
Updated template with more information.
